version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./.db/data:/var/lib/postgresql/data
  #      - ./.db/tsearch_data:/usr/share/postgresql/13/tsearch_data

  server:
    container_name: server
    build:
      target: development
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./src:/usr/server/src
#      - ./.env:/usr/server/.env
      - ./package.json:/usr/server/package.json
      - ./node_modules:/usr/server/node_modules
      - ./.db/csv:/usr/server/.db/csv
    command: npm run dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - ./.env
    depends_on:
      - postgres
